[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
  "lxml",
  "docxtpl",
  "requests",
  "openai",
]
name = "cvextract"
version = "0.0.6"

[tool.pytest.ini_options]
testpaths = ["tests"]
